# SPDX-FileCopyrightText: 2023 KOINSLOT, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Lint Espressif Component
on:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: check out repository
      uses: actions/checkout@v3

    - name: cache build files
      uses: actions/cache@v3
      with:
        key: ${{ github.repository }}/${{ github.sha }}/build
        path: |
          **/build
          .devkit
          compile_commands.json

    - name: lint component
      run: docker run -v $PWD:$PWD -w $PWD -e SDKCONFIG_DEFAULTS='sdkconfig.ci' kywy/devkit:latest sh -c 'make --file /devkit/Makefile lint'
