# SPDX-FileCopyrightText: 2023 KOINSLOT, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Version, Publish, Release
on:
  pull_request:
    types:
    - closed
    branches:
    - main
jobs:
  version:
    if: github.event.pull_request.merged == true
    uses: KOINSLOT-Inc/devkit/.github/workflows/version.reusable.yaml@main
    secrets: inherit
  publish:
    if: github.event.pull_request.merged == true
    needs: version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: tag
      run: |
        git describe --tags
        echo "tag=$(git describe --tags)" >> "$GITHUB_OUTPUT"
    - uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - id: meta
      uses: docker/metadata-action@v4.4.0
      with:
        images: kywy/devkit
    - uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: kywy/devkit:latest,kywy/devkit:${{ steps.tag.outputs.tag }}
        labels: ${{ steps.meta.outputs.labels }}
  release:
    if: github.event.pull_request.merged == true
    needs: publish
    uses: KOINSLOT-Inc/devkit/.github/workflows/release.reusable.yaml@main
    secrets: inherit
