# SPDX-FileCopyrightText: 2023 KOINSLOT, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Test Espressif Component
on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: check out repository
      uses: actions/checkout@v3

    - name: cache build files
      uses: actions/cache@v3
      with:
        key: ${{ github.repository }}/build/${{ github.sha }}
        path: |
          **/build
          .devkit
          compile_commands.json

    - name: test component
      run: docker run -v $PWD:$PWD -w $PWD -e SDKCONFIG_DEFAULTS='sdkconfig.ci' kywy/devkit:latest sh -c 'make --file /devkit/Makefile test'
