# SPDX-FileCopyrightText: 2023 KOINSLOT, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Upload Espressif Component
on:
  workflow_call:
jobs:
  upload_component:
    runs-on: ubuntu-latest
    steps:

    - name: check out with tags
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: get version
      id: version
      run: |
        git describe --tags
        echo "version=$(git describe --tags | sed -E -e 's/-[0-9]+-/-/' -e 's/^v//')" >> "$GITHUB_OUTPUT"

    - name: upload component to the component registry
      uses: espressif/upload-components-ci-action@v1
      with:
        name: ${{ github.event.repository.name }}
        version: ${{ steps.version.outputs.version }}
        namespace: "kywyerik"
        api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
